Repository pooranjoyb/popShop, pull requests merged in 2024-06, with the labels that each got.

#159 Feature/update signup process
  package-lock.json
  package.json
  src/components/Button.tsx
  src/index.css
  src/pages/Auth/Auth.tsx
  src/utils/schema.ts
Labels: level1, gssoc

#162 Cart slice
  src/components/Navbar.tsx
  src/pages/Shop/ProductDetail.tsx
  src/utils/features/cart/cartSlice.ts
  src/utils/features/store.ts
Labels: level2, gssoc, utility, critical

#175 Saving User Data in db.
  src/pages/Auth/Auth.tsx
  src/utils/schema.ts
Labels: level2, gssoc, utility

#179 [Feature] Enhance Authentication Screen #156
  src/pages/Auth/Auth.tsx
  src/tailwind/output.css
  tailwind.config.js
Labels: ui, level2, gssoc

#181 Close dropdown on choosing an option
  src/components/Navbar.tsx
Labels: level1, gssoc, utility

#176 Added a contact page and terms & condition page
  src/browserRoutes/routes/Routes.tsx
  src/components/Footer.tsx
  src/pages/Contact/Contact.tsx
  src/pages/T&C/TermsCond.tsx
Labels: ui, enhancement, gssoc, level3

#180 feat: added functionality to navbar
  src/components/Floating_Nav.tsx
  src/components/Footer.tsx
  src/components/Navbar.tsx
  src/pages/Home/Home.tsx
Labels: ui, level2, gssoc

#184 Edit profile functionality added.
  src/pages/Profile/EditProfileModal.tsx
  src/pages/Profile/Profile.tsx
Labels: ui, gssoc, level3, utility, critical

#196 Fix : Styling and Space
  src/pages/Home/Home.tsx
  src/pages/Profile/Profile.tsx
  src/pages/Shop/Shop.tsx
Labels: ui, level1, gssoc

#194 Implemented contact feature and added FQA section.
  package-lock.json
  package.json
  src/pages/Contact/Contact.tsx
  src/pages/Contact/FQA.tsx
  src/tailwind/output.css
Labels: ui, gssoc, level3, utility

#208 Checkout Page Developed
  src/browserRoutes/routes/Routes.tsx
  src/pages/Cart/Cart.tsx
  src/pages/Checkout/Checkout.tsx
  src/tailwind/output.css
Labels: ui, enhancement, level2, gssoc

#193 Cart Management
  src/App.tsx
  src/components/Product.tsx
  src/pages/Cart/Cart.tsx
  src/pages/Shop/ProductDetail.tsx
  src/utils/client.ts
Labels: ui, gssoc, level3, utility, critical

#218 Fix: Made shop header responsive.
  package-lock.json
  src/pages/Shop/Shop.tsx
Labels: ui, level1, gssoc, utility

#216 update cart fetch data from supabase
  package-lock.json
  package.json
  src/components/Navbar.tsx
  src/pages/Cart/Cart.tsx
Labels: ui, gssoc, level3, utility

#223 remove item from cart success
  src/pages/Cart/Cart.tsx
Labels: ui, level2, gssoc, utility, critical

#225 Cart quantity
  src/pages/Cart/Cart.tsx
  src/pages/Cart/QuantityButton.tsx
  src/pages/Shop/ProductDetail.tsx
Labels: ui, level2, gssoc, utility, critical

#211 fix: ui container responsiveness
  package-lock.json
  package.json
  src/browserRoutes/routes/Routes.tsx
  src/components/Floating_Nav.tsx
  src/components/Footer.tsx
  src/components/Navbar.tsx
  src/index.css
  src/pages/Auth/Auth.tsx
  src/pages/Contact/Contact.tsx
  src/pages/Contact/FQA.tsx
  src/pages/Error.tsx
  src/pages/Home/Home.tsx
  src/pages/Profile/EditProfileModal.tsx
  src/pages/Profile/Profile.tsx
  src/pages/Shop/ProductDetail.tsx
  src/pages/Shop/Shop.tsx
  src/pages/T&C/TermsCond.tsx
  src/tailwind/output.css
  src/utils/features/cart/cartSlice.ts
  src/utils/features/store.ts
  src/utils/schema.ts
  tailwind.config.js
Labels: ui, level1, gssoc

#229 toast message while removing items from cart
  src/pages/Cart/Cart.tsx
Labels: ui, level1, gssoc

#230 feat: Subscribe component added
  src/components/Footer.tsx
  src/pages/Home/Home.tsx
Labels: ui, level1, gssoc

#231 Summary
  src/pages/Checkout/Checkout.tsx
Labels: ui, level2, gssoc, utility

#243 fixed bug: profile not updating
  src/pages/Profile/EditProfileModal.tsx
Labels: level2, gssoc, utility

#242 Added My Orders Page
  src/browserRoutes/routes/Routes.tsx
  src/components/Navbar.tsx
  src/pages/Profile/MyOrders.tsx
Labels: ui, gssoc, level3

#239 added `orders` while user checkout their cart and remove cart items a…
  package-lock.json
  package.json
  src/pages/Checkout/Checkout.tsx
  src/pages/Shop/ProductDetail.tsx
  src/utils/features/cart/cartSlice.ts
Labels: gssoc, level3, utility

#245 implementing search in products
  src/pages/Shop/Shop.tsx
Labels: bug, ui, level2, utility, critical

#247 Dynamic filter opetion on products
  src/components/Product.tsx
  src/pages/Shop/Shop.tsx
Labels: ui, level1, gssoc

#195 fixed to allow uesr to explore without login
  deploy.yaml
  package-lock.json
  package.json
  public/images/cookies.png
  public/images/license.png
  public/images/t&c.jpg
  src/App.tsx
  src/browserRoutes/routes/Routes.tsx
  src/components/Floating_Nav.tsx
  src/components/Footer.tsx
  src/components/Navbar.tsx
  src/components/Product.tsx
  src/pages/Auth/Auth.tsx
  src/pages/Auth/ProtectedRoute.tsx
  src/pages/Cart/Cart.tsx
  src/pages/Cart/QuantityButton.tsx
  src/pages/Checkout/Checkout.tsx
  src/pages/Home/Home.tsx
  src/pages/Orders/MyOrders.tsx
  src/pages/Profile/EditProfileModal.tsx
  src/pages/Profile/Profile.tsx
  src/pages/Shop/ProductDetail.tsx
  src/pages/Shop/Shop.tsx
  src/pages/T&C/TermsCond.tsx
  src/tailwind/output.css
  src/utils/client.ts
  src/utils/features/cart/cartSlice.ts
Labels: level1, gssoc

#251 Fixed the cart price issue in the navbar
  src/components/Navbar.tsx
Labels: ui, level2, gssoc, utility, critical

#257 add product detailes while ordering
  src/pages/Checkout/Checkout.tsx
Labels: level1, gssoc, utility

#261 Show password
  .gitignore
  package-lock.json
  package.json
  src/pages/Auth/Auth.tsx
Labels: ui, level1, gssoc

#250 minor ui + utility bugs fixes
  src/components/Floating_Nav.tsx
  src/components/Footer.tsx
  src/components/Navbar.tsx
  src/pages/Cart/Cart.tsx
  src/pages/Orders/MyOrders.tsx
  src/pages/Shop/Shop.tsx
Labels: bug, ui, level2, gssoc

#278 Cart glitch
  .gitignore
  dist/assets/browser-OhFq99mK.js
  dist/assets/index-BacZYtc7.js
  dist/assets/index-DHNlpPs2.css
  dist/icon.ico
  dist/images/dress.jpg
  dist/images/fashion.jpg
  dist/images/footer.jpg
  dist/images/hero.png
  dist/images/winter1.jpg
  dist/images/winter2.jpg
  dist/images/winter3.jpg
  dist/images/winter4.jpg
  dist/index.html
  dist/logo.png
  src/components/Navbar.tsx
Labels: bug, ui, level1, gssoc

#271 Added Google OAuth
  package-lock.json
  package.json
  src/browserRoutes/routes/Routes.tsx
  src/pages/Auth/Auth.tsx
  src/pages/Auth/Oauth.tsx
Labels: ui, gssoc, level3, utility, critical
