Repository pooranjoyb/popShop, pull requests merged in 2024-07, with the labels that each got.

#285 Resolved Update-Profile-Details
  src/pages/Profile/EditProfileModal.tsx
Labels: bug, ui, level2, gssoc, utility

#290 added functionality to coupons
  src/pages/Cart/Cart.tsx
Labels: enhancement, level1, gssoc, utility

#311 added Return/Exchange feature
  package-lock.json
  package.json
  src/pages/Orders/MyOrders.tsx
  src/pages/Orders/ReturnExchangePopup.tsx
Labels: ui, level2, gssoc

#316 Created Filter Feature
  src/pages/Shop/Shop.tsx
Labels: level1, gssoc, utility

#314 fixes issue #306 & #302
  src/components/Navbar.tsx
  src/pages/Cart/Cart.tsx
  src/pages/Shop/ProductDetail.tsx
Labels: ui, level2, gssoc

#319 search based on product name
  package-lock.json
  src/pages/Shop/Shop.tsx
Labels: bug, ui, level1, gssoc, utility

#330 updated SuperAdmin Dashboard
  package-lock.json
  package.json
  src/admin/Dashboard.tsx
Labels: ui, gssoc, level3, critical

#335 Product add in admin panel
  src/admin/AddProduct.tsx
Labels: ui, gssoc, level3, utility, critical

#340 Added profile image button
  src/components/Navbar.tsx
  src/pages/Profile/Profile.tsx
  src/utils/schema.ts
Labels: ui, gssoc, level3, utility

#339 Protected Admin route added
  src/admin/AdminLayout/Sidebar.tsx
  src/browserRoutes/routes/Routes.tsx
  src/pages/AdminPage/Login.tsx
  src/utils/features/Auth/authSlice.ts
Labels: ui, gssoc, level3, utility

#346 Admin and google dp
  src/admin/AdminLayout/AdminLayout.tsx
  src/admin/Transactions.tsx
  src/components/Navbar.tsx
  src/pages/Profile/Profile.tsx
Labels: ui, level2, gssoc, utility

#341 [Feature] Adding an AI Chatbot to the Website
  flow (1).json
  index.html
  public/chatbot.jpg
  public/images/Chatbot Icon
  src/components/TopButton/TopButton.css
Labels: ui, good first issue, level2, gssoc, utility

#359 Real time data in dashboard
  package-lock.json
  package.json
  src/admin/Dashboard.tsx
Labels: ui, level2, gssoc, utility

#361 Hamburger minor fixes
  src/components/Navbar.tsx
  src/pages/Shop/Shop.tsx
Labels: level2, gssoc, utility

#375 Issue #352 fixed. Added Google Language Translator.
  src/components/Footer.tsx
  src/components/GoogleTranslateComponent.tsx
Labels: level1, good first issue, gssoc, utility

#366 make admin dashboard responsive
  src/admin/AdminLayout/AdminLayout.tsx
  src/admin/AdminLayout/AdminNavbar.tsx
  src/admin/AdminLayout/Sidebar.tsx
  src/admin/Dashboard.tsx
  src/admin/admin.css
Labels: ui, level1, gssoc

#371 product card as well as img
  src/components/Product.tsx
  src/pages/Profile/EditProfileModal.tsx
  src/pages/Shop/Shop.tsx
Labels: ui, level1, gssoc
