Repository pooranjoyb/popShop, pull requests merged in 2024-05, with the labels that each got.

#8 zod validation integration
  package-lock.json
  package.json
  src/pages/Auth/Auth.tsx
  src/utils/schema.ts
Labels: level2, GSSOC'24, utility

#44 Adding UI rating on product page including numbers of rating
  package-lock.json
  package.json
  postcss.config.cjs
  src/pages/Shop/ProductDetail.tsx
Labels: ui, level1, gssoc

#50 raect-icons added
  package-lock.json
  package.json
  src/components/Footer.tsx
  src/components/Navbar.tsx
Labels: ui, level1, gssoc

#58 [FIX] Added Toast Notification on 'Add to Cart' Button
  package-lock.json
  package.json
  src/App.tsx
  src/components/Button.tsx
  src/pages/Shop/ProductDetail.tsx
  src/pages/Shop/Shop.tsx
Labels: ui, level1, gssoc

#54 Feat-responsive
  public/images/dress.jpg
  public/images/dress.png
  public/images/footer.avif
  public/images/footer.jpg
  src/components/Footer.tsx
  src/components/Head.tsx
  src/pages/Cart/Cart.tsx
  src/pages/Home/Home.tsx
  src/pages/Shop/Shop.tsx
  src/tailwind/output.css
Labels: ui, level2, gssoc

#64 feat: automate greeting using github action
  .github/workflows/greetings.yml
Labels: level1, gssoc, utility

#61 Fixed Quantity Button
  src/pages/Cart/Cart.tsx
  src/pages/Cart/QuantityButton.tsx
  src/pages/Shop/ProductDetail.tsx
Labels: ui, level1, gssoc

#73 Fixed search feature
  package-lock.json
  src/pages/Shop/Shop.tsx
Labels: gssoc, utility

#75 Added Redux Persist
  CONTRIBUTING.md
  package-lock.json
  package.json
  src/components/Navbar.tsx
  src/main.tsx
  src/pages/Auth/Auth.tsx
  src/pages/Auth/ProtectedRoute.tsx
  src/utils/features/Auth/authSlice.ts
  src/utils/features/store.ts
Labels: level2, gssoc, utility, critical

#66 Animation added for HomePage
  package-lock.json
  package.json
  src/pages/Home/Home.tsx
Labels: ui, level2, gssoc

#90 feat: forgot password, schema
  src/pages/Auth/Auth.tsx
  src/utils/schema.ts
Labels: level2, gssoc, utility

#83 feat: profile page
  src/browserRoutes/routes/Routes.tsx
  src/components/Navbar.tsx
  src/pages/Profile/Profile.tsx
  src/tailwind/output.css
Labels: ui, level2, gssoc

#87 Feature:-Animated Loading page
  src/components/Loader/Loader.css
  src/components/Loader/Loader.tsx
Labels: level1, gssoc, utility

#91 add_pr_template_with_issue_template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/document.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/ISSUE_TEMPLATE/refactor_code.yml
  .github/pull_request_template.md
Labels: level2, gssoc, utility

#112 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: level1, gssoc, utility

#111 feat-#82: Refining Protected Routes.
  src/pages/Auth/ProtectedRoute.tsx
Labels: level1, gssoc, utility

#123 created autocomment-pr-merge.yml
  .github/workflows/autocomment-pr-merge.yml
Labels: level1, gssoc, utility

#96 removed bug 'when authenticated we still can go to auth page '
  src/App.tsx
  src/browserRoutes/routes/Routes.tsx
  src/components/Navbar.tsx
  src/components/Product.tsx
  src/main.tsx
  src/pages/Auth/Auth.tsx
  src/pages/Auth/ProtectedRoute.tsx
  src/pages/Home/Home.tsx
  src/pages/Layout.tsx
Labels: level1, gssoc, utility, critical

#124 Enhance validation and error handling in Auth component
  src/pages/Auth/Auth.tsx
  src/utils/schema.ts
Labels: level1, gssoc, utility

#134 TopButton
  src/browserRoutes/routes/Routes.tsx
  src/components/TopButton.css
  src/components/TopButton.tsx
  src/tailwind/output.css
Labels: ui, level1, gssoc

#136 updates
  src/browserRoutes/routes/Routes.tsx
  src/components/Button.tsx
  src/components/Footer.tsx
  src/components/Navbar.tsx
  src/components/TopButton/TopButton.css
  src/components/TopButton/TopButton.tsx
  src/pages/Cart/Cart.tsx
  src/pages/Shop/Shop.tsx
Labels: ui, level2, gssoc

#150 fixing animation
  src/pages/Home/Home.tsx
Labels: ui, level1, gssoc

#144 added buttons on Products page and home screen
  src/components/Product.tsx
Labels: ui, level1, gssoc

#154 Feat: Enter Triggers Login
  src/pages/Auth/Auth.tsx
Labels: level1, gssoc, utility

#157 Adding an eye button
  src/components/Product.tsx
  src/pages/Auth/Auth.tsx
  src/pages/Home/Home.tsx
Labels: ui, level1, gssoc
